version: "3.8"

services:
    ####################################
    # Temporary MySQL Database
    ####################################
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: product
    ####################################
    # Pytest on Books Service
    ####################################
    books-pytest:
        build:
            context: ../
            dockerfile: ci/Dockerfile.test
        depends_on:
            - mysql
        environment:
            db_conn_books: mysql+mysqlconnector://root:root@mysql:3306
            disable_amqp: 1
